
default_platform :ios

fastlane_require "fastlane-plugin-brew"
fastlane_require "fastlane-plugin-versioning"

def keychain_name
  "MatchKeychain"
end

def bundle_identifier_beta
  ENV["APP_IDENTIFIER"] + ".beta"
end

def all_bundle_ids(identifier)
  if ENV["APP_EXTENSIONS"]
    ENV["APP_EXTENSIONS"]
      .split(",")
      .map { |type| identifier + ".#{type}" }
      .unshift(identifier)
      .join(",")
  else
    identifier
  end
end

def merge_additional_settings(base, env_key)
  additional = ENV[env_key]
  unless additional.nil? || additional.empty?
    json_data = JSON.parse(additional)
    json_data = json_data.transform_keys(&:to_sym) if json_data.is_a?(Hash)
    base.merge!(json_data)
  end
  base
end

def build_settings
  merge_additional_settings(
    {
      scheme: ENV["APP_SCHEME"],
      output_name: ENV["APP_NAME"],
      output_directory: "./build_output/"
    },
    "ADDITIONAL_BUILD_SETTINGS"
  )
end

def code_signing_settings
  merge_additional_settings(
    {
      username: ENV["USER_EMAIL"],
      git_url: ENV["MATCH_GIT_URL"],
      shallow_clone: true,
      clone_branch_directly: true,
      keychain_password: ENV["MATCH_PASSWORD"],
    },
    "ADDITIONAL_CODE_SIGNING_SETTINGS"
  )
end

def tests_settings
  merge_additional_settings(
    {
      skip_build: true,
      scheme: ENV["APP_SCHEME"],
      code_coverage: true,
      result_bundle: true,
    },
    "ADDITIONAL_TESTS_SETTINGS"
  )
end


desc "Download development certificate and provisioning profiles."
lane :provisioning do
  sync_code_signing(code_signing_settings.merge({
    team_id: ENV["TEAM_ID"],
    git_branch: ENV["MATCH_GIT_BRANCH"],
    readonly: true,
    app_identifier: all_bundle_ids(ENV["APP_IDENTIFIER"])
  }))
end

desc "Update appstore certificate and provisioning profiles for release. Options: - create_branch: Boolean. If true and CUSTOMERS_BRANCH is specified, it will create it (it's needed for the first time)."
lane :update_release_provisioning do |options|
  if ENV["APP_IDENTIFIER_CUSTOMER"] == nil
    sync_code_signing(code_signing_settings.merge({
      git_branch: ENV["MATCH_GIT_BRANCH"],
      app_identifier: all_bundle_ids(ENV["APP_IDENTIFIER"]),
      team_id: ENV["TEAM_ID"],
      type: "appstore"
    }))
  else
    sync_code_signing(code_signing_settings.merge({
      git_branch: ENV["CUSTOMERS_BRANCH"] || ENV["MATCH_GIT_BRANCH"],
      app_identifier: all_bundle_ids(ENV["APP_IDENTIFIER_CUSTOMER"]),
      team_id: ENV["TEAM_ID_CUSTOMER"],
      type: "appstore",
      clone_branch_directly: options[:create_branch] ? options[:create_branch] : true
    }))
  end
end

desc "Update certificate and provisioning profiles. Options: - include_release: Boolean. If true, it will also update release certificate and provisioning profiles.; - create_branch: Boolean. If true and CUSTOMERS_BRANCH is specified, it will create it (it's needed for the first time)."
lane :update_provisioning do |options|
  begin
    sh "git clone --single-branch --depth 1 --no-checkout #{ENV["DEVICE_LIST_GIT_URL"]} device-list && cd device-list && git checkout #{ENV["DEVICE_LIST_GIT_BRANCH"]} device-list.txt"
    code_signing_settings_private = code_signing_settings.merge({
      team_id: ENV["TEAM_ID"],
      git_branch: ENV["MATCH_GIT_BRANCH"]
    })
    register_devices(
      devices_file: "fastlane/device-list/device-list.txt",
      username: ENV["USER_EMAIL"],
      team_id: ENV["TEAM_ID"]
    )
    # DEBUG
    sync_code_signing(code_signing_settings_private.merge({
      app_identifier: all_bundle_ids(ENV["APP_IDENTIFIER"])
    }))
    # BETA
    sync_code_signing(code_signing_settings_private.merge({
      type: "appstore",
      app_identifier: all_bundle_ids(bundle_identifier_beta)
    }))
    # RELEASE
    if options[:include_release] == true then
      update_release_provisioning(create_branch: options[:create_branch])
    end
  ensure
    if Dir.exist?('device-list')
      sh "rm -rf device-list"
    end
  end
end

desc "Runs all the tests and report status to GitHub."
lane :test do
  dependencies
  generate_graphql_operations
  run_tests(tests_settings)
end

desc "Submit a beta build to App Store connect. Options: - build_number: Integer. Custom build number (skips auto-increment from TestFlight).; - version_number: String. Custom version number (skips ENV['VERSION_NUMBER'])."
lane :beta do |options|
  app_store_connect_api_key
  dependencies
  generate_graphql_operations
  bump(is_beta: true, build_number: options[:build_number], version_number: options[:version_number])
  configure_keychain
  sync_code_signing(code_signing_settings.merge({
    type: "appstore",
    git_branch: ENV["MATCH_GIT_BRANCH"],
    app_identifier: all_bundle_ids(bundle_identifier_beta),
    team_id: ENV["TEAM_ID"],
    keychain_name: keychain_name,
    readonly: true
  }))
  build_ios_app(build_settings.merge({
    configuration: "Beta"
  }))
  upload_to_testflight(
    app_identifier: bundle_identifier_beta,
    team_id: ENV["ASC_TEAM_ID"],
    username: ENV["USER_EMAIL"],
    skip_waiting_for_build_processing: true,
    changelog: ENV["CHANGELOG"]
  )
end

desc "Submit a release build to App Store connect. Options: - build_number: Integer. Custom build number (skips auto-increment from TestFlight).; - version_number: String. Custom version number (skips ENV['VERSION_NUMBER'])."
lane :release do |options|
  app_store_connect_api_key
  dependencies
  generate_graphql_operations
  bump(build_number: options[:build_number], version_number: options[:version_number])
  configure_keychain
  sync_code_signing(code_signing_settings.merge({
    type: "appstore",
    git_branch: ENV["CUSTOMERS_BRANCH"] || ENV["MATCH_GIT_BRANCH"],
    app_identifier: all_bundle_ids(ENV["APP_IDENTIFIER_CUSTOMER"] || ENV["APP_IDENTIFIER"]),
    team_id: ENV["TEAM_ID_CUSTOMER"] || ENV["TEAM_ID"],
    keychain_name: keychain_name,
    readonly: true
  }))
  build_ios_app(build_settings)
  upload_to_testflight(
    app_identifier: ENV["APP_IDENTIFIER_CUSTOMER"] || ENV["APP_IDENTIFIER"],
    team_id: ENV["ASC_TEAM_ID_CUSTOMER"] || ENV["ASC_TEAM_ID"],
    username: ENV["USER_EMAIL"],
    skip_waiting_for_build_processing: true
  )
end

desc "Create release and beta apps in developer portal & ITC. Options: - skip_release_app: Boolean. If true, it will create only BETA app.; - company_name: String. Company name for the app. Is needed for the creation of the first app in new account."
lane :create_apps do |options|
  create_apps_online(skip_release_app: options[:skip_release_app], company_name: options[:company_name])
end

desc "Create release and beta apps of given type in developer portal. Options: - skip_release_app: Boolean. If true, it will create only BETA app."
lane :create_apps_for_extension do |options|
  extensions = (ENV["APP_EXTENSIONS"] || "").split(",").map(&:strip)
  extensions.each do |extension|
    create_apps_online(type: extension, skip_release_app: options[:skip_release_app])
  end
end

desc "Generate GraphQL operations."
lane :generate_graphql_operations do
  if ENV["APOLLO_CODEGEN_CONFIG_PATH"] != nil then
    sh(
      "cd ..
      Scripts/apollo-ios-cli generate --path #{ENV["APOLLO_CODEGEN_CONFIG_PATH"]}"
    )
  end
end

private_lane :bump do |options|
  latest_build = (latest_testflight_build_number(
    app_identifier: options[:is_beta] ? bundle_identifier_beta : ENV["APP_IDENTIFIER_CUSTOMER"] || ENV["APP_IDENTIFIER"],
    team_id: options[:is_beta] ? ENV["ASC_TEAM_ID"] : ENV["ASC_TEAM_ID_CUSTOMER"] || ENV["ASC_TEAM_ID"],
    username: ENV["USER_EMAIL"]
  ) || 0)

  if options[:build_number]
    build_number = options[:build_number].to_i
    unless build_number > latest_build
      UI.important("Warning: Custom build number #{build_number} is not higher than the latest TestFlight build number #{latest_build}. Upload may fail.")
    end
  else
    build_number = latest_build + 1
  end

  increment_build_number(
    build_number: build_number,
    skip_info_plist: true
  )

  version = if options[:version_number]
              options[:version_number].to_s
            else
              (ENV["VERSION_NUMBER"] || "1.0.0").split("-").first
            end

  increment_version_number_in_xcodeproj(
    version_number: version,
    scheme: ENV["APP_SCHEME"],
    **(ENV["FL_BUILD_NUMBER_PROJECT"] ? {xcodeproj: ENV["FL_BUILD_NUMBER_PROJECT"]} : {})
  )
end

private_lane :create_apps_online do |options|
  # Debug
  if ENV["APP_IDENTIFIER_CUSTOMER"] || options[:skip_release_app] == true then
    create_app_online(
      username: ENV["USER_EMAIL"],
      app_identifier: ENV["APP_IDENTIFIER"] + (options[:type] ? "." + options[:type] : ""),
      app_name: ENV["APP_NAME"] + (options[:type] ? " " + options[:type] : ""),
      team_id: ENV["TEAM_ID"],
      itc_team_id: ENV["ASC_TEAM_ID"],
      skip_itc: true
    )
  end
  # Beta
  create_app_online(
    username: ENV["USER_EMAIL"],
    app_identifier: bundle_identifier_beta + (options[:type] ? "." + options[:type] : ""),
    app_name: ENV["APP_NAME"] + " BETA" + (options[:type] ? " " + options[:type] : ""),
    team_id: ENV["TEAM_ID"],
    itc_team_id: ENV["ASC_TEAM_ID"],
    skip_itc: options[:type] ? true : false
  )
  # Release
  if options[:skip_release_app] != true then
    create_app_online(
      username: ENV["USER_EMAIL"],
      app_identifier: (ENV["APP_IDENTIFIER_CUSTOMER"] || ENV["APP_IDENTIFIER"]) + (options[:type] ? "." + options[:type] : ""),
      app_name: ENV["APP_NAME"] + (options[:type] ? " " + options[:type] : ""),
      team_id: ENV["TEAM_ID_CUSTOMER"] || ENV["TEAM_ID"],
      itc_team_id: ENV["ASC_TEAM_ID_CUSTOMER"] || ENV["ASC_TEAM_ID"],
      skip_itc: options[:type] ? true : false,
      **(options[:company_name] ? {company_name: options[:company_name]} : {})
    )
  end
end

private_lane :dependencies do
  ENV["XCODE_VERSION"] && xcodes(version: ENV["XCODE_VERSION"], select_for_current_build_only: true)
  brew(command: File.exist?("../Brewfile") ? "bundle" : "install swiftlint")
  cocoapods(try_repo_update_on_error: true) if File.exist?("../Podfile")
end

private_lane :configure_keychain do
  create_keychain(
    name: keychain_name,
    password: ENV["MATCH_PASSWORD"],
    unlock: false,
    timeout: 3600
  )
end
